### ISSUE TITLE
There needs to be a clean way to shut down threads

### ISSUE THREAD

**Issue by AndrejMitrovic** [Geod24/localrest#22]
Currently, the only way to shut down a spawned RemoteAPI thread is to kill off the main thread (which will send a `OwnerTerminated` message to its child threads).

But, in Agora we use explicit shutdowns for all of our tests:

https://github.com/bpfkorea/agora/blob/7f6e46fc20f39b9c7d2abe63b53d900619386376/source/agora/test/Base.d#L164

This is insufficient, because the `shutdown()` method there only dumps / deallocates / destroys internal handles, but the main thread associated with each node continues to run (and will continue to listen to events).

There needs to be a way to tell the node (thread) to stop processing events. A simple `ctrl.shutdown()` API could do the job.

**Comment by Geod24** [comment]
Damn I really think we had this implemented... Looks like the [ownership mechanism was never implemented](https://github.com/Geod24/localrest/blob/756af07d51ed7deadb912d753ff1f2bf58e3e4b5/source/geod24/LocalRest.d#L330-L334).
