### ISSUE TITLE
Implement unbuffered channels

### ISSUE THREAD

**Issue by Geod24** [Geod24/localrest#41]
Implement the default channel semantic of Go, unbuffered channels that provide direct hands off semantics.

In essence, when a write / read happens on a channel that is unbuffered, the control is transferred (handed off) directly to another fiber, possibly one waiting for data.

See the order of things in this example:
```golang
package main

import "fmt"

func notBomberman(messages chan int) {
    fmt.Println("+ Pong()");
    <- messages
    fmt.Println("+ Pong()");
    <- messages
    fmt.Println("+ Pong()");
    <- messages
}

func main() {
    messages := make(chan int)
    go notBomberman(messages)
    fmt.Println("* Ping()")
    messages <- 42
    fmt.Println("* Ping()")
    messages <- 42
    fmt.Println("* Ping()")
    messages <- 42
    fmt.Println("* Boom")
}
```

**Comment by omerfirmak** [comment]
This should be closed since #96 is merged.
