### ISSUE TITLE
Ensures a stable finish to client requests when a request is dropped

### ISSUE THREAD

**Issue by MichaelKim20** [Geod24/localrest#55]
The node does not have a timeout set. 
And, when requests have been dropped during the time set by the 'sleep' command. 
The client will continue to wait until a response is received. 

Let's solve this and eliminate unnecessary resources immediately.

**Comment by AndrejMitrovic** [comment]
But that is the purpose of a timeout. To handle the case when a request does not complete within a reasonable time. In the real world there should always be a timeout set for a node.

**Comment by MichaelKim20** [comment]
Oh, I see. 
We'll be careful about dropping a request from a node that doesn't have a timeout.
Then we can close the issue.

**Comment by AndrejMitrovic** [comment]
Maybe @Geod24 has more input, but personally I can't think of use-cases for a node which doesn't have a timeout.

**Comment by MichaelKim20** [comment]
> Maybe @Geod24 has more input, but personally I can't think of use-cases for a node which doesn't have a timeout.

Yes, I see. I'll check it out slowly.

**Comment by Geod24** [comment]
> In the real world there should always be a timeout set for a node.

Yes.

**Comment by Geod24** [comment]
Indeed, this issue is not valid. If a node doesn't have a timeout, it exposes itself to wait forever. Perhaps we should set a (very high) default so that it has less chance to happen by mistake.
